# Generated by Django 5.1.6 on 2025-07-14 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_laveur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=20, unique=True)),
                ('nom_client', models.CharField(blank=True, max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant total payé par le client', max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('commission_laveur', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('part_entreprise', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('statut', models.CharField(choices=[('payé', 'Payé'), ('non_payé', 'Non payé'), ('en_cours', 'En cours')], default='en_cours', max_length=20)),
                ('mode_paiement', models.CharField(choices=[('espèce', 'Espèce'), ('mobile', 'Mobile Money'), ('carte', 'Carte Bancaire')], default='espèce', max_length=20)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
                ('laveur', models.ForeignKey(limit_choices_to={'role': 'laveur'}, on_delete=django.db.models.deletion.PROTECT, related_name='factures_realisees', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.service')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_heure'],
            },
        ),
    ]
