# Generated by Django 5.1.6 on 2025-07-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_facture_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.service'),
        ),
    ]
