services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn lavagesamy.wsgi --log-file -"
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.kptksubouclvisizinsu:Samy2@25@aws-0-eu-north-1.pooler.supabase.com:6543/postgres?sslmode=require
      - key: SECRET_KEY
        sync: false  # À définir dans le dashboard Render
      - key: DEBUG
        value: "False"
      - key: DB_PASSWORD
        sync: false  # À définir dans le dashboard Render